In [1]:
# Loading the dataset using pandas

import pandas as pd

df = pd.read_csv('Customer_Shopping_Behaviour.csv')

In [2]:
# Returns first top 10 Rows
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1370,36,Female,Shirt,Clothing,88,Wisconsin,M,Orange,Winter,1.0,Yes,Free Shipping,No,No,18,PayPal,Monthly
1,329,32,Male,Sweater,Clothing,37,Alaska,XL,Pink,Fall,5.0,No,Standard,Yes,Yes,2,PayPal,Annually
2,3449,58,Male,Shorts,Clothing,89,Montana,L,Orange,Fall,3.0,Yes,Express,Yes,Yes,17,Debit Card,Monthly
3,501,58,Female,Pants,Clothing,84,Michigan,XL,Olive,Fall,1.0,Yes,Free Shipping,Yes,Yes,47,Credit Card,Weekly
4,2017,35,Male,Sandals,Footwear,67,Missouri,S,Peach,Spring,5.0,No,Free Shipping,Yes,Yes,38,Credit Card,Monthly

In [3]:
# Returns last top 10 Rows
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
7245,3394,52,Female,Hoodie,Clothing,94,Montana,M,Red,Winter,4.0,No,2-Day Shipping,Yes,Yes,50,Gift Card,Monthly
7246,3378,64,Female,Sneakers,Footwear,76,Alabama,XL,Purple,Spring,5.0,Yes,Express,Yes,Yes,7,Credit Card,Annually
7247,2564,29,Male,Gloves,Accessories,32,Massachusetts,S,Silver,Fall,5.0,No,Standard,Yes,Yes,18,PayPal,Monthly
7248,2238,69,Male,Sandals,Footwear,57,South Carolina,S,Red,Summer,5.0,No,2-Day Shipping,No,No,33,Debit Card,Weekly
7249,3097,49,Female,T-shirt,Clothing,88,Iowa,M,Teal,Summer,5.0,Yes,Free Shipping,No,No,47,Credit Card,Monthly

In [4]:
# Random data (record) from Dataset

df.sample()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3585,1231,44,Female,Sweater,Clothing,88,Maryland,S,Yellow,Winter,5.0,No,Free Shipping,Yes,Yes,2,PayPal,Weekly

In [5]:
# Shape of Dataset using df.shape
df.shape  # No of Rows and Columns
# df.shape[0] # No of Rows
# df.shape[1] # No of Columns

(7250, 18)

In [6]:
# Concise summary of a dataframe using df.info()

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7250 entries, 0 to 7249
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             7250 non-null   int64
 1   Age                     7250 non-null   int64
 2   Gender                  7250 non-null   str
 3   Item Purchased          7250 non-null   str
 4   Category                7250 non-null   str
 5   Purchase Amount (USD)   7250 non-null   int64
 6   Location                7250 non-null   str
 7   Size                    7250 non-null   str
 8   Color                   7250 non-null   str
 9   Season                  7250 non-null   str
 10  Review Rating           7207 non-null   float64
 11  Subscription Status     7250 non-null   str
 12  Shipping Type           7250 non-null   str
 13  Discount Applied        7250 non-null   str
 14  Promo Code Used         7250 non-null   str
 15  Previous Purchases      7250 non-null   int64
 16  Payment Method          7250 non-null   str
 17  Frequency of Purchases  7250 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 1019.7 KB

In [7]:
# Descriptive Statistics of DataFrame using .describe() for Numeriacl Summary

df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,7250.000000,7250.000000,7250.000000,7207.000000,7250.000000
mean,1951.137517,44.007172,60.581793,4.056889,25.336000
std,1123.105753,15.348077,23.352357,1.095919,14.342112
min,1.000000,18.000000,20.000000,1.000000,1.000000
25%,982.250000,31.000000,40.000000,4.000000,13.000000
50%,1958.000000,44.000000,61.000000,4.000000,26.000000
75%,2921.750000,57.000000,81.000000,5.000000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [8]:
# Descriptive Statistics of DataFrame using .describe() for Categorical Summary

df.describe(include=['object', 'string'])

,Gender,Item Purchased,Category,Location,Size,Color,Season,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Payment Method,Frequency of Purchases
count,7250,7250,7250,7250,7250,7250,7250,7250,7250,7250,7250,7250,7250
unique,2,25,4,50,4,25,4,2,6,2,2,5,4
top,Male,Jewelry,Clothing,Alabama,L,Green,Winter,No,Free Shipping,Yes,Yes,Credit Card,Monthly
freq,4186,347,3255,168,1867,325,2242,5270,2455,5909,5909,3132,3510

In [9]:
# Checking if missing data or null values are present in the dataset

df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             43
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [10]:
# Imputing missing values in Review Rating column with the median rating of the Item Purchased

item_median = df.groupby('Item Purchased')['Review Rating'].transform('median')

df['Review Rating'] = df['Review Rating'].fillna(item_median)

In [11]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [12]:
# Renaming columns according to snake casing for better readability and documentation

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [13]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [14]:
# create a new column age_group
bins = [18, 30, 45, 60, 100]
labels = ['Young Adult', 'Adult', 'Middle Aged', 'Senior']
#  Age     Age	Groups
# 18–29	   Young Adult
# 30–44	   Adult
# 45–59	   Middle-Aged
# 60+	   Senior

df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=False)

In [15]:
df[['age','age_group']].head(10)

   age    age_group
0   36        Adult
1   32        Adult
2   58  Middle Aged
3   58  Middle Aged
4   35        Adult
5   19  Young Adult
6   52  Middle Aged
7   55  Middle Aged
8   34        Adult
9   20  Young Adult

In [16]:
print(df['frequency_of_purchases'].unique())

<StringArray>
['Monthly', 'Annually', 'Weekly', 'Bi-Weekly']
Length: 4, dtype: str

In [17]:
# create new column purchase_frequency_days

frequency_mapping = {
    'Weekly': 7,
    'Fortnightly': 14,
    'Bi-Weekly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Every 3 Months': 90,
    'Annually': 365
    }

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [18]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       30                Monthly
1                      365               Annually
2                       30                Monthly
3                        7                 Weekly
4                       30                Monthly
5                       14              Bi-Weekly
6                       30                Monthly
7                        7                 Weekly
8                       30                Monthly
9                      365               Annually

In [19]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0               No              No
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7               No              No
8              Yes             Yes
9              Yes             Yes

In [20]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [21]:
# Dropping promo code used column

df = df.drop('promo_code_used', axis=1)

In [22]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [23]:
df.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1370,36,Female,Shirt,Clothing,88,Wisconsin,M,Orange,Winter,1.0,Yes,Free Shipping,No,18,PayPal,Monthly,Adult,30
1,329,32,Male,Sweater,Clothing,37,Alaska,XL,Pink,Fall,5.0,No,Standard,Yes,2,PayPal,Annually,Adult,365
2,3449,58,Male,Shorts,Clothing,89,Montana,L,Orange,Fall,3.0,Yes,Express,Yes,17,Debit Card,Monthly,Middle Aged,30
3,501,58,Female,Pants,Clothing,84,Michigan,XL,Olive,Fall,1.0,Yes,Free Shipping,Yes,47,Credit Card,Weekly,Middle Aged,7
4,2017,35,Male,Sandals,Footwear,67,Missouri,S,Peach,Spring,5.0,No,Free Shipping,Yes,38,Credit Card,Monthly,Adult,30
5,186,19,Male,Sandals,Footwear,53,Pennsylvania,S,Black,Winter,4.0,Yes,Free Shipping,Yes,16,Credit Card,Bi-Weekly,Young Adult,14
6,2768,52,Female,Jeans,Clothing,91,Rhode Island,M,Green,Winter,5.0,No,Free Shipping,Yes,5,Credit Card,Monthly,Middle Aged,30
7,3489,55,Female,Socks,Clothing,75,Maine,M,Green,Winter,3.0,Yes,2-Day Shipping,No,28,Credit Card,Weekly,Middle Aged,7
8,2319,34,Male,T-shirt,Clothing,57,Idaho,XL,Violet,Summer,4.0,No,Express,Yes,26,Credit Card,Monthly,Adult,30
9,2800,20,Male,Shoes,Footwear,28,North Carolina,S,Gold,Spring,3.0,No,2-Day Shipping,Yes,36,PayPal,Annually,Young Adult,365

In [24]:
#Exporting data to CSV File
df.to_csv(r"C:\Users\Asus\Desktop\Customer Shopping Behaviour End to End Project New\Customer_Shopping_Behaviour_New_Cleaned_Data.csv", index=False)